name: Build and deploy Python project to Azure Function App - datascraper-fa

on:
  push:
    branches:
      - prod
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."  # Root of your app
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (for tooling)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build dependencies in Azure Functions Docker image
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/app" \
            -w /app \
            mcr.microsoft.com/azure-functions/python:4-python3.11 \
            bash -c "
              pip install --upgrade pip && \
              pip install -r requirements.txt --target .python_packages/lib/site-packages
            "

      - name: Zip artifact for deployment
        run: |
          mkdir upload
          shopt -s dotglob extglob
          cp -r !(upload|.git|.github|.venv|.vscode|.funcignore) upload/
          cd upload
          zip -r ../release.zip . -x "*.git*" "*.venv*" "*.github*" "*.vscode*" "*.funcignore" "__pycache__/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9653AF349B11434FB560AFFAEDA83E5F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD91F7CC22DD47D5BD7F4AC157D89CB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0EFF101E2AD4C1A931101D4E5C4FDED }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "datascraper-fa"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
